In [1]:
import numpy as np
from tensorflow.keras.models import load_model

In [2]:
model = load_model("final.h5")

In [7]:
def str_to_sudoku(s):
    return np.array([int(c)/4.5-1 for c in s]).reshape(9,9)

In [27]:
from tqdm import tqdm
def sudoku_predict(puzzle):
    sudoku = str_to_sudoku(puzzle)
    remains = (sudoku==-1).sum()
    for _ in tqdm(range(remains)):
        predict = -1
        probability = -1
        index = -1
        output = model.predict(sudoku.reshape(1,9,9,1))
        output = output.squeeze()
        for i in range(81):
            if sudoku[i//9, i%9] == -1:
                proba = np.max(output[i])
                if(proba > probability):
                    probability = proba
                    predict = np.argmax(output[i])
                    index = i
        sudoku[index//9, index%9] = (predict+1)/4.5-1
    return ((sudoku+1)*4.5).astype('int32')

In [28]:
sudoku = "050314060870009403643507192007805210410900000025061907790250840004096005030108670"
assert len(sudoku) == 81
pred = sudoku_predict(sudoku)
print(pred)
print("\nRow Sum   :", pred.sum(axis=0))
print("\nColumn Sum:", pred.sum(axis=1))

100%|██████████████████████████████████████████████████████████████████████████████████| 34/34 [00:01<00:00, 29.65it/s]

[[2 5 9 3 1 4 7 6 8]
 [8 7 1 6 2 9 4 5 3]
 [6 4 3 5 8 7 1 9 2]
 [9 6 7 8 3 5 2 1 4]
 [4 1 8 9 7 2 5 3 6]
 [3 2 5 4 6 1 9 8 7]
 [7 9 6 2 5 3 8 4 1]
 [1 8 4 7 9 6 3 2 5]
 [5 3 2 1 4 8 6 7 9]]

Row Sum   : [45 45 45 45 45 45 45 45 45]

Column Sum: [45 45 45 45 45 45 45 45 45]


In [29]:
sudoku2 = "160094382005000010320807096286030070000080920000021408958100000700000000043970850"
assert len(sudoku2) == 81
pred = sudoku_predict(sudoku2)
print(pred)
print("\nRow Sum   :", pred.sum(axis=0))
print("\nColumn Sum:", pred.sum(axis=1))

100%|██████████████████████████████████████████████████████████████████████████████████| 43/43 [00:01<00:00, 39.70it/s]

[[1 6 7 5 9 4 3 8 2]
 [8 9 5 2 6 3 7 1 4]
 [3 2 4 8 1 7 5 9 6]
 [2 8 6 4 3 9 1 7 5]
 [4 7 1 6 8 5 9 2 3]
 [5 3 9 7 2 1 4 6 8]
 [9 5 8 1 4 6 2 3 7]
 [7 1 2 3 5 8 6 4 9]
 [6 4 3 9 7 2 8 5 1]]

Row Sum   : [45 45 45 45 45 45 45 45 45]

Column Sum: [45 45 45 45 45 45 45 45 45]
